/**
 * @file ShardIo.cpp
 * @brief Implementation of qpudatashard CSV read/write
 */

#include "ShardIo.hpp"
#include <fstream>
#include <sstream>
#include <iostream>
#include <iomanip>

namespace windminer {
namespace io {

/**
 * @brief Read canyon data from CSV
 * Expected format: canyon_id,lat,lon,h_m,w_m,theta_c_deg
 */
std::vector<geometry::Canyon> ShardIo::readCanyons(const std::string& filepath) {
    std::vector<geometry::Canyon> canyons;
    std::ifstream file(filepath);
    
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open canyon file: " << filepath << std::endl;
        return canyons;
    }
    
    std::string line;
    // Skip header
    std::getline(file, line);
    
    while (std::getline(file, line)) {
        std::stringstream ss(line);
        std::string token;
        geometry::Canyon canyon;
        
        try {
            std::getline(ss, token, ','); canyon.id = token;
            std::getline(ss, token, ','); canyon.latitude = std::stod(token);
            std::getline(ss, token, ','); canyon.longitude = std::stod(token);
            std::getline(ss, token, ','); canyon.height_m = std::stod(token);
            std::getline(ss, token, ','); canyon.width_m = std::stod(token);
            std::getline(ss, token, ','); canyon.orientation_deg = std::stod(token);
            
            canyons.push_back(canyon);
        } catch (const std::exception& e) {
            std::cerr << "Warning: Skipping malformed line: " << line << std::endl;
        }
    }
    
    return canyons;
}

/**
 * @brief Write qpudatashard records to CSV
 * RFC-4180 compliant
 */
bool ShardIo::writeShards(
    const std::string& filepath,
    const std::vector<QpuDataShard>& records
) {
    std::ofstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot write to shard file: " << filepath << std::endl;
        return false;
    }
    
    // Write Header
    file << "nodeid,assettype,region,lat,lon,avgwindspeed_ms,dominantwind_from,"
         << "season,netheight_m,netwidth_m,netporosity,expected_capture_kg_per_year,"
         << "maintenance_visits_per_year,ecoimpactscore,karmaperunit,notes\n";
    
    // Write Records
    file << std::fixed << std::setprecision(6);
    for (const auto& rec : records) {
        file << rec.nodeid << ","
             << rec.assettype << ","
             << rec.region << ","
             << rec.latitude << ","
             << rec.longitude << ","
             << rec.avgwindspeed_ms << ","
             << rec.dominantwind_from << ","
             << rec.season << ","
             << rec.netheight_m << ","
             << rec.netwidth_m << ","
             << rec.netporosity << ","
             << rec.expected_capture_kg_per_year << ","
             << rec.maintenance_visits_per_year << ","
             << rec.ecoimpactscore << ","
             << rec.karmaperunit << ","
             << "\"" << rec.notes << "\"\n";
    }
    
    return true;
}

/**
 * @brief Convert EcoImpactResult to QpuDataShard
 */
QpuDataShard ShardIo::ecoResultToShard(
    const impact::EcoImpactResult& eco_result,
    const geometry::Canyon& canyon,
    const geometry::Windnet& net
) {
    QpuDataShard shard;
    
    shard.nodeid = "PHX-WINDNET-" + eco_result.canyon_id;
    shard.assettype = "UrbanWindTrashNet";
    shard.region = "Phoenix-AZ-US";
    shard.latitude = canyon.latitude;
    shard.longitude = canyon.longitude;
    shard.avgwindspeed_ms = 2.5; // Default Phoenix Uimp*
    shard.dominantwind_from = "W"; // Simplified
    shard.season = "Year-Round";
    shard.netheight_m = net.height_m;
    shard.netwidth_m = net.width_m;
    shard.netporosity = net.porosity;
    shard.expected_capture_kg_per_year = eco_result.capture_mass_kg_year;
    shard.maintenance_visits_per_year = 52; // Weekly
    shard.ecoimpactscore = eco_result.eco_impact_score;
    shard.karmaperunit = eco_result.karma_per_unit;
    shard.notes = "Auto-generated by Windminer v1.0";
    
    return shard;
}

/**
 * @brief Generate prototype shard filename
 */
std::string ShardIo::generateShardFilename(
    const std::string& city,
    const std::string& version
) {
    return "windnet_" + city + "_prototype" + version + ".csv";
}

} // namespace io
} // namespace windminer
